## 1 import numpy


In [2]:
import numpy as np

## 2 print numpy version


In [ ]:
np.__version__

## 3 create a vector that length is 10


In [ ]:
np.zeros(10)

## 4 check the memory size of any array


In [ ]:
arr = np.arange(1,20, dtype=np.int32)
arr.size * arr.itemsize

## 5 get help info


In [ ]:
np.info(np.add)

## 6 creat a ndarray that all values is zero except the index of 5 element value is 1


In [ ]:
arr = np.zeros(10)
arr[5] = 1
arr

## 7 create a matrix that values are 10 - 49

In [ ]:
arr = np.arange(10, 50)
arr.reshape(1, -1)

## 8 reverse a matrix


In [ ]:
arr = np.arange(1,10)
arr[::-1]

## 9 create a matrix that 3x3 and the valus are 0-8


In [ ]:
arr = np.arange(0,9).reshape(3,3)
arr

## 10 find the element whose value is not zero


In [ ]:
arr = np.array([1,2,0,0,4,0])
arr.nonzero()


## error
## 11 create a diagonal matrix


In [ ]:
arr = np.eye(3, dtype=np.int32)
arr


## error
## 12 create a random ndarray of 3x3x3 that the dimentions are three


In [ ]:
arr = np.random.random((3,3,3))
arr


## 13 create a ndarray of 10x10 and find the max and min value


In [ ]:
arr = np.random.random((10,10))
min = arr.min()
max = arr.max()
min, arr


## 14 create a random ndarray and find the ave


In [ ]:
arr = np.random.random(30)
arr.mean()


## 15 create a ndarray that the first and last values are zero


In [ ]:
arr = np.zeros((3,3))
arr[1:-1,1:-1] = 1
arr


## 16 fill the bound with zero


In [ ]:
import numpy as np
arr = np.arange(1,10)
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr
tarr = np.array([[1,2,3],[4,5,6]])
tarr = np.pad(tarr, pad_width=2, mode='constant', constant_values=0)
tarr


## 17 what's the output?


In [ ]:
np.nan == np.nan  
np.inf > np.nan  
np.nan - np.nan  


## 18 generate a checkboard matrix


In [ ]:
arr = np.zeros((8,8), dtype=np.int32)
arr
arr[0::2, 1::2] = 1
arr[1::2, 0::2] = 1
arr


## 19 get position


In [ ]:
arr = np.ones((6,7,8), dtype=np.int32)
arr
np.unravel_index(100, (6,7,8))

arr = np.array([[1,2,3],[4,5,6]])
arr = np.tile(arr, (2,2))
arr


## 20 create a 8x8 checkboard


In [ ]:
arr = np.array([[1,0],[0,1]])
arr
carr = np.tile(arr, (4,4))
carr


## 21 normalization


In [ ]:
arr = np.array([[1,5,10],[2,10,20]])
arr
farr = np.astype(arr, np.float64)
farr
narr = (farr - farr.min()) / (farr.max() - farr.min())
narr


## 22 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype


In [ ]:
color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte, 1), ('a', np.ubyte, 1)])
color


## 23 matrix multiple


In [ ]:
marr = np.dot(np.ones((5,3)), np.ones((3,2)))
marr


## 24 指定元素取反


In [ ]:
arr = np.arange(1,10)
arr
arr[(arr > 3) & (arr < 8)] *= -1
arr


## 25 

In [ ]:
sum(range(5), -1)


## 26 **


In [ ]:
arr = np.arange(1,5)
arr
arr ** arr


## 27


In [ ]:
arr = np.array(1)
narr = np.array(1)
arr / narr


## 28


In [ ]:
arr = np.random.uniform(-10, +10, +10)
arr = np.ceil(np.abs(arr))
np.copysign(arr, arr)


## 29 找到共同元素


In [ ]:
narr = np.random.uniform(-10, 10, 10)
# print(narr)
marr = np.random.uniform(-10, 10, 10)
# print(marr)
ncarr = np.ceil(np.abs(narr))
mcarr = np.ceil(np.abs(marr))
np.intersect1d(ncarr, mcarr)


## 30


In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)


## 31 get today, yesterday, tormorrow


In [ ]:
td = np.datetime64('today', 'D')
td
yd = td - np.timedelta64(1, 'D')
yd
tmd = td + np.timedelta64(1, 'D')
tmd


## 32 get some days


In [ ]:
darr = np.arange('2003-05', '2003-06', dtype='datetime64[D]')
darr


## 33 no copy


In [ ]:
arr = np.ones(3) * 1
tarr = np.ones(3) * 2
tarr
oarr = np.ones(3) * 3
np.add(arr, tarr, out=oarr)
oarr

np.divide(oarr, tarr, out=arr)
arr

np.negative(arr, out=arr)
arr
np.negative(arr[1:4], out=arr[0:2])
arr


## 34 使用不同的方法提取随机矩阵的正整数部分


In [ ]:
arr = np.random.uniform(-10, 10, (5, 2))
arr


### a) ceil


In [ ]:
abarr =np.abs(arr) 
carr = np.ceil(abarr)
carr


### b) floor


In [ ]:
farr = np.floor(abarr)
farr


### c) as type


In [ ]:
asarr = abarr.astype(int)
asarr


### d) trunc


In [ ]:
tarr = np.trunc(abarr)
tarr


### e) %


In [ ]:
marr = (abarr - abarr % 1)
marr


## 35 创建一个 5x5 的矩阵，每行的值为0-4


In [ ]:
farr = np.zeros((5,5))
farr
farr += np.arange((5))
farr    

## 36 通过一个迭代器生成一个向量


In [3]:
ls = [x for x in range(1,10)]
ls
iarr = np.fromiter(ls, dtype=int, count=-1)
iarr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 37 创建一个长度为10的随机向量

In [8]:
larr = np.random.random(10)
larr

array([0.05339335, 0.3855941 , 0.42762736, 0.80521014, 0.76006263,
       0.88036171, 0.41184477, 0.37290297, 0.21163663, 0.07550614])

## 38 创建向量并排序

In [9]:
arr = np.random.random(10)
np.sort(arr)

array([0.06213795, 0.08196755, 0.22650612, 0.31819533, 0.55068608,
       0.60635338, 0.70155273, 0.77387416, 0.91282143, 0.95830479])

## 39 比 sum 更快的求和方式

In [ ]:
arr = np.arange(1, 10)
arr
np.add.reduce(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 40 检查两个随机数组 A & B 是否相等 

## 41 Create read only ndarray 

In [13]:
arr = np.arange(0, 10)
arr.flags.writeable = False
arr[0] = 123

ValueError: assignment destination is read-only

## 42 将笛卡尔坐标下的一个 10x2 的矩阵转为 极坐标形式

In [ ]:
arr = np.random.random((10,2))
arr


array([[0.20547813, 0.06517773],
       [0.48894797, 0.66077394],
       [0.93638108, 0.01790594],
       [0.36608379, 0.55776546],
       [0.26175562, 0.29091397],
       [0.69326143, 0.92027429],
       [0.51041695, 0.03789095],
       [0.83080675, 0.75670425],
       [0.6394208 , 0.74833993],
       [0.62981593, 0.55108729]])