# n_d_array -> numerical dimentional array

In [ ]:
import numpy as np

a = np.array([1,2,3])
a.ndim  # 1

b = np.array([[1,2,3]])
b.ndim  # 2


2

# operate the arr

In [ ]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
# the index starts with zero
arr[2,1]

arr[:,0]

array([1, 4, 7])

# dimention

In [ ]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr.shape   # (4,3)
arr.size    # 12
arr.ndim    # 2

arr1 = np.array([1,23,4,4,5])
arr1.ndim   # 1
arr1.size   # 3
arr1.shape  #(3,)
arr1.dtype  # dtype('int64')

dtype('int64')

# primary operation

In [30]:
import numpy as np

np.zeros(2) # array([0., 0.])
np.ones(3)
np.empty(5)

np.arange(3)
np.arange(3,6,2)
np.linspace(1,10, num=3)

array([ 1. ,  5.5, 10. ])