## index

In [8]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

[arr > 5]
(arr > 5)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [9]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

arr[arr > 5]

array([6, 7, 8, 9])

In [20]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

arr[(arr > 5) | (arr == 5)]

#[(arr > 5) | (arr == 5)]

array([5, 6, 7, 8, 9])

In [15]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [31]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
      
f = np.nonzero(arr < 5)
f
arr[f]

d = np.nonzero(arr > 52)
d
d[0].size
type(d[0])
d

(array([], dtype=int64), array([], dtype=int64))