## content
- stack
- split
- view
- calculate

## stack

In [9]:
import numpy as np

varr = np.array([[1,2,3],[4,5,6]])
harr = np.array([[7,8,9],[10,11,12]])
varr, harr

v = np.vstack((varr,harr))
v
h = np.hstack((harr,varr))
h

np.concatenate((harr,varr), axis=1)

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

## split

In [6]:
import numpy as np

arr = np.arange(1,25).reshape(2,12)
arr

hs = np.hsplit(arr, 3)
hs


[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

## view

In [12]:
import numpy as np

arr = np.arange(1,25).reshape(2,12)
arr

barr = arr[1,:]
barr

barr[0] = 100
barr    # array([100,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])
# array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
#        [100,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24]])
arr

carr = arr.copy()
carr[1][1] = 100
carr
arr


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [100,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24]])