# content
- base calculate

## base calculate

In [22]:
import numpy as np

arr = np.ones(2, dtype = int)
arr
arr.sum()

barr = np.array([2,3])
barr

barr / arr
barr * arr
barr % arr
barr // arr
barr.std()
np.sum(barr)
np.std(aarr)

aarr = np.arange(1,10)
aarr
aarr.sum(axis=0)

tarr = np.array([[1,2,3], [4,5,6]])
t = tarr.sum(axis=0)
t   # import numpy as np

arr = np.ones(2, dtype = int)
arr
arr.sum()

barr = np.array([2,3])
barr

barr / arr
barr * arr
barr % arr
barr // arr
barr.std()
np.sum(barr)
np.std(aarr)

aarr = np.arange(1,10)
aarr
aarr.sum(axis=0)

tarr = np.array([[1,2,3], [4,5,6]])
tarr.sum(axis=0)    # array([5, 7, 9])

tarr.max(axis=0)    # array([4, 5, 6])
tarr.min(axis=1)


array([1, 4])

In [ ]:
arr = np.array([[2,3],[4,5]])
odarr = np.array([1,1])
# array([[3, 4],
#        [5, 6]])
arr + odarr

tdarr = np.array([[1,1]])
# array([[3, 4],
#        [5, 6]])
arr + tdarr

array([[3, 4],
       [5, 6]])

In [30]:
tarr = np.ones((3,2))
tarr
tarr.shape

(3, 2)

## random

In [34]:
rdm = np.random.default_rng()
rdm.random(3)

rdm.random((3,2))
rdm.random((3,2,1))

array([[[0.47008059],
        [0.89488662]],

       [[0.87986449],
        [0.9615317 ]],

       [[0.9759661 ],
        [0.2544924 ]]])

In [37]:
rdm.integers(5, size=(3,3))

array([[0, 0, 3],
       [1, 3, 2],
       [1, 1, 0]])