In [5]:
import numpy as np

ndarr = np.array([1,1,2,3,4,5,6,6,6,10])
np.unique(ndarr)

v, ls = np.unique(ndarr, return_index=True)
v, ls

(array([ 1,  2,  3,  4,  5,  6, 10]), array([0, 2, 3, 4, 5, 6, 9]))

In [4]:
v,ls = np.unique(ndarr, return_counts=True)
v, ls

(array([ 1,  2,  3,  4,  5,  6, 10]), array([2, 1, 1, 1, 1, 3, 1]))

In [7]:
nd2arr = np.array([[1,2,3],[4,5,6],[7,8,9], [1,2,3]])
nd2arr
np.unique(nd2arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.unique(nd2arr, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.unique(nd2arr, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])